brain_two/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("todo_list_list")),
        name="home",
    ),
]

todos/urls.py
from django.urls import path
from .views import (
    TodoListView,
    TodoListDetail,
    TodoListCreate,
    TodoListUpdate,
    TodoListDelete,
    TodoItemCreate,
    TodoItemUpdate,
)

urlpatterns = [
    path("", TodoListView.as_view(), name="todo_list_list"),
    path("<int:pk>/", TodoListDetail.as_view(), name="todo_list_detail"),
    path("create/", TodoListCreate.as_view(), name="todo_list_create"),
    path("<int:pk>/edit/", TodoListUpdate.as_view(), name="todo_list_update"),
    path(
        "<int:pk>/delete/",
        TodoListDelete.as_view(),
        name="todo_list_delete",
    ),
    path("items/create/", TodoItemCreate.as_view(), name="todo_item_create"),
    path(
        "items/<int:pk>/edit/",
        TodoItemUpdate.as_view(),
        name="todo_item_update",
    ),
]

todos/models.py
from django.db import models


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.name)


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList",
        related_name="items",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return str(self.task)

todos/views.py
# from django.shortcuts import render
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse_lazy
from .models import TodoList, TodoItem


class TodoListView(ListView):
    model = TodoList
    template_name = "todos/list.html"


class TodoListDetail(DetailView):
    model = TodoList
    template_name = "todos/detail.html"


class TodoListCreate(CreateView):
    model = TodoList
    template_name = "todos/create.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])


class TodoListUpdate(UpdateView):
    model = TodoList
    template_name = "todos/update.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])


class TodoListDelete(DeleteView):
    model = TodoList
    template_name = "todos/delete.html"
    success_url = reverse_lazy("todo_list_list")


class TodoItemCreate(CreateView):
    model = TodoItem
    template_name = "items/create.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])


class TodoItemUpdate(UpdateView):
    model = TodoItem
    template_name = "items/update.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])

todos/templates/items/create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo Lists</title>
  </head>
  <body>
    <main>
      <div>
        <h1>Create a new item</h1>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button>Create</button>
        </form>
      </div>
    </main>
  </body>
  {% comment %} <pre>{% debug %}</pre> {% endcomment %}
</html>

todos/templates/items/update.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo Lists</title>
  </head>
  <body>
    <main>
      <div>
        <h1>Update item</h1>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button>Update</button>
        </form>
      </div>
    </main>
  </body>
  {% comment %} <pre>{% debug %}</pre> {% endcomment %}
</html>

todos/templates/todos/create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo Lists</title>
  </head>
  <body>
    <main>
      <div>
        <h1>Create a new list</h1>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button>Create</button>
        </form>
      </div>
    </main>
  </body>
  {% comment %} <pre>{% debug %}</pre> {% endcomment %}
</html>

todos/templates/todos/delete.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo Lists</title>
  </head>
  <body>
    <main>
      <div>
        <h1>Are you sure?</h1>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button>Delete</button>
        </form>
      </div>
    </main>
  </body>
  {% comment %} <pre>{% debug %}</pre> {% endcomment %}
</html>

todos/templates/todos/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ todolist.name }} List</title>
  </head>
  <body>
    <main>
      <div>
        <h1>{{ todolist.name }}</h1>
        <p>
          <a href="{% url 'todo_list_update' todolist.id %}">Edit</a>
        </p>
        <p>
          <a href="{% url 'todo_list_delete' todolist.id %}">Delete</a>
        </p>
        <h2>Tasks</h2>
        <table>
          <thead>
            <th>Task</th>
            <th>Due date</th>
          </thead>
          <tbody>
            {% for item in todolist.items.all %}
              <tr>
                <td>
                  <a href="{% url 'todo_item_update' item.id %}">{{ item.task }}</a>
                </td>
                <td>{{ item.due_date }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </main>
  </body>
  {% comment %} <pre>{% debug %}</pre> {% endcomment %}
</html>

todos/templates/todos/list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo Lists</title>
  </head>
  <body>
    <main>
      <div>
        <h1>My Lists</h1>
        <p>
          <a href="{% url 'todo_list_create' %}">Create a new list</a>
        </p>
        <p>
          <a href="{% url 'todo_item_create' %}">Create a new item</a>
        </p>
        <table>
          <thead>
            <th>Name</th>
            <th>Number of items</th>
          </thead>
          <tbody>
            {% for list in todolist_list %}
              <tr>
                <td>
                  <a href="{% url 'todo_list_detail' list.id %}">{{ list.name }}</a>
                </td>
                <td>{{ list.items.all|length }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </main>
  </body>
  {% comment %} <pre>{% debug %}</pre> {% endcomment %}
</html>

todos/templates/todos/update.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo Lists</title>
  </head>
  <body>
    <main>
      <div>
        <h1>Update list</h1>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button>Update</button>
        </form>
      </div>
    </main>
  </body>
  {% comment %} <pre>{% debug %}</pre> {% endcomment %}
</html>